# Generated by Django 4.1.3 on 2022-11-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=999)),
                ('Quantity', models.IntegerField(max_length=999)),
                ('Price', models.IntegerField(max_length=999999)),
            ],
        ),
    ]
