# Generated by Django 4.1.3 on 2022-11-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barnmgt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
