# Generated by Django 4.1.3 on 2022-11-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profiler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiler',
        ),
        migrations.AlterField(
            model_name='barnmgt',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barnmgt',
            name='Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
