# Generated by Django 4.1.3 on 2022-11-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_profiler_alter_barnmgt_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=90)),
                ('Length', models.IntegerField()),
                ('Breadth', models.IntegerField()),
                ('Email', models.EmailField(max_length=999)),
                ('Phone_no', models.IntegerField()),
                ('Tags', models.CharField(max_length=10)),
            ],
        ),
    ]
