# Generated by Django 4.1.3 on 2022-11-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profiler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiler',
            new_name='Profile',
        ),
    ]
